### ISSUE TITLE
Historias de usuario. Crear. 

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/VoteCounting_3a#2]
Crear historias de Usuario. 

Una vez debatidas y aprobadas por todos nosotros se transcribirán en https://github.com/Arquisoft/VoteCounting_3a/wiki/Historias-de-usuario

RECORDAR: Deben ser aprobadas por **TODOS.** _En representación de los profesores_. 
- [x] Historia 1
- [x] Historia 2
- [x] Historia 3
- [x] Historia 4
- [x] Historia 5

@Palaskan @davidglezz @raulbt @PiruzUA

**Comment by AmirHT** [comment]
**Como** _usuario final_ **quiero** ver estadísticas en forma de texto plano.
Posibles palabras: total, votos, %, 

**Como** _usuario final_ **quiero** ver estadísticas en forma de gráfica
Posibles palabras: total, votos, %, <img... > 

**Como** _usuario final desarrollador_ **quiero** quiero poder consultar las estadísticas a través de una API.
Posibles palabras: Json ?, votos, total, etc. 

**Como** _miembro de la junta electoral_ **quiero** Activar el recuento de votos y recibir confirmación de que se ha activado. 
Posibles palabras: Servicio, activado, etc. 

**Como** _miembro de la junta electoral_ **quiero** Desactivar el recuento de votos y recibir confirmación de que se ha Desactivado. 
Posibles palabras: Servicio, desactivado, etc. 

@Palaskan  Opinad
@davidglezz Opinad 
@raulbt  Opinad
@PiruzUA Opinad

**Comment by davidglezz** [comment]
Bien.

**Comment by raulbt** [comment]
A mi me parecen correctas esas 5.

**Comment by AmirHT** [comment]
ok, entonces cierro la tarea, están copiadas en la WIKI.
