### ISSUE TITLE
Control de Votaciones activas/finalizadas (modulo de actualizacion de datos)

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/VoteCounting_3a#25]
Debe haber POR EJEMPLO en sesión una lista o mapa de votaciones activas y posiblemente otra para finalizadas. 

Para que el método de parar realizar recuentos acceda a el y que el sistema sepa que votaciones debe actualizar. 

El de finalizadas para saber que votaciones tenemos para "servir"

**Comment by davidglezz** [comment]
Ojo, en sesión no, sería más bien a nivel de aplicación.
Eso esta parcialmente implementado, esta implementado pero no es bean y no se como se comportara luego. de momento se guarda en una variable estática.
