### ISSUE TITLE
Encontrar varios JS para la web

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/VoteCounting_3a#5]
**Deben** ser usables, accesibles vamos en general que tenga un... **CPM APROVED**.

**Comment by davidglezz** [comment]
#### jQuery
- Ajax
- Manipulación Dom
- Es dependencia de Bootstrap

#### Bootstrap
- Base CSS
- Componentes típicos como menús, botones, ..

#### page.js
- Navegación e historial. (SPA)

#### doT.js
- Motor de plantillas.

#### 3d.js
- Gráficos. (Barras, circulares ...)
