### ISSUE TITLE
Modelo de Datos y BD

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/VoteCounting_3a#8]
Con diagrama de modelo **aprobado por el resto de participantes del grupo.** ponerlo en este enlace https://github.com/Arquisoft/VoteCounting_3a/wiki/Modelo-de-Datos
Debe _dar soporte a **todas** las funcionalidades_ que vamos a tener. 
Script de creación de la _Base de datos_ con la informacion del modelo.
Y en general, toda la capa de persistencia... a ser posible con @autowired

**Comment by davidglezz** [comment]
Esto creo que puede solucionarnos el problema que tuvimos en la primera entrega con el autowire.
http://stackoverflow.com/questions/29629393/spring-boot-jpa-autowired-jpa-repository-is-null

**Comment by raulbt** [comment]
Modifique totalmente el acceso al modelo de datos.

**Comment by AmirHT** [comment]
De aquí  nacen los issues #30 y #26
