### ISSUE TITLE
Calculo de estadisticas y % que vamos a mostrar. 

### ISSUE THREAD

**Issue by AmirHT** [Arquisoft/VoteCounting_3a#9]
Toda la lógica que da soporte a los cálculos que vamos a realizar. Se irán marcando  según se vayan implementando. 

Mostrar datos de VOTOS. 
- [x] Votos Globales
- [ ] Cuantas y % de personas votaron Perro y cuantas Gato
- [x] Votos Por Colegio. 
- [ ] De cada colegio, cuantos (personas y %) votaron por Gato y cuantas por Perro
- [x] Votos Por Región. 
- [ ] De cada región, cuantos (personas y %) votaron por Gato y cuantas por Perro

Por Mayorías 
- [ ] Colegios
- [ ] Cuantos y % de Colegios votaron por Gato / Perro
- [ ] Región 
- [ ] Cuantas y % de Regiones que votaron por Gato / Perro

Si se os ocurren mas agregad. @Arquisoft/course1516_i2a

**Comment by raulbt** [comment]
Yo creo que el resto de campos se sacan calculando in situ al obtener los valores en la propia web.
